# Generated by Django 5.2.3 on 2025-06-19 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_discussion_delete_advertisement_delete_badge_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_at', 'title', 'hub', 'category', 'author'], 'verbose_name': 'Discussion', 'verbose_name_plural': 'Discussions'},
        ),
        migrations.AddField(
            model_name='discussion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='blog.category'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='blog.hub'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='tag',
            field=models.ManyToManyField(blank=True, related_name='discussions', to='blog.tag'),
        ),
    ]
