# Generated by Django 5.2.3 on 2025-06-19 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_discussion_options_discussion_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_at', 'title', 'hub', 'category'], 'verbose_name': 'Discussion', 'verbose_name_plural': 'Discussions'},
        ),
    ]
