# Generated by Django 5.2.3 on 2025-06-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discussion',
            options={'ordering': ['-created_at', 'title', 'hub'], 'verbose_name': 'Discussion', 'verbose_name_plural': 'Discussions'},
        ),
        migrations.RemoveField(
            model_name='discussion',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
