# Generated by Django 5.2.3 on 2025-07-01 16:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_tag_options_alter_post_tags_alter_tag_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowingHub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='blog.hub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_hubs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Following Hub',
                'verbose_name_plural': 'Following Hubs',
                'unique_together': {('user', 'hub')},
            },
        ),
        migrations.CreateModel(
            name='FollowingUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('following_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Following User',
                'verbose_name_plural': 'Following Users',
                'unique_together': {('user', 'following_user')},
            },
        ),
    ]
